; SCANDISK.INI
;
; Questo file contiene le impostazioni per personalizzare il programma
; ScanDisk.


; -------------------------------------------------------------------
; La sezione [ENVIRONMENT] contiene le seguenti impostazioni che determinano
; gli aspetti generali del funzionamento di ScanDisk:
;
; Display      Configura ScanDisk in moda tale che sia possibile eseguirlo
;	       con uno schermo specifico. Lo schermo predefinito Š Auto
;	       (ScanDisk si adatta allo schermo corrente).
;
; Mouse        Attiva o disattiva il supporto per il mouse. Il valore
;	       predefinito Š On.
;
; ScanTimeOut  Determina se ScanDisk debba rilevare i ritardi di attesa del
;	       disco mentre esegue un esame della superficie. Il valore
;	       predefinito Š Off.
;
; NumPasses    Determina quante volte ScanDisk deve controllare ogni cluster
;	       durante un esame della superficie. Il valore predefinito Š 1.
;
; LabelCheck   Determina se ScanDisk debba controllare la presenza di
;	       caratteri non validi nelle etichette dei volumi. Il valore
;	       predefinito Š Off.

[ENVIRONMENT]
   Display     = Auto   ; Auto, Mono, Color, Off
   Mouse       = On     ; On, Off
   ScanTimeOut = Off    ; On, Off
   NumPasses   = 1	; Da 1 a 65.535 (Lento Š superiore a 10)
   LabelCheck  = Off    ; On, Off


; -------------------------------------------------------------------
; La sezione [CUSTOM] determina il funzionamento di ScanDisk quando
; viene avviato con l'opzione /CUSTOM. E' possibile modificarne le
; impostazioni per creare una versione "personalizzata" di ScanDisk che pu•
; essere particolarmente utile per eseguire ScanDisk da un file batch. Le
; impostazioni [CUSTOM] sono:
;
; DriveSummary	Determina se ScanDisk debba visualizzare le informazioni di
;		riepilogo a schermo intero dopo l'esame di ogni unit….
;		Il valore predefinto Š Auto (ScanDisk visualizza il riepilogo
;		solo se rileva errori nell'unit…).
;
; AllSummary	Determina se ScanDisk debba visualizzare le informazioni di
;		riepilogo a schermo intero dopo l'esame di tutte le unit….
;		Il valore predefinto Š Auto (ScanDisk visualizza il riepilogo
;		solo se rileva errori in un'unit…).
;
; Surface	Determina quando ScanDisk debba eseguire un esame della
;		superficie:
;		   Never    (Predefinito) Non esegue l'esame della superficie.
;		   Always   Esegue l'esame senza chiedere conferma.
;		   Prompt   Esegue l'esame dopo aver chiesto conferma.
;		L'opzione della riga di comando /SURFACE annulla l'effetto di
;		questo parametro.
;
; CheckHost	Determina se ScanDisk debba esaminare l'unit… host prima di
;		controllare eventuali unit… compresse in essa contenute:
;		   Never    (Predefinito) Non esegue l'esame dell'unit… host.
;		   Always   Esegue l'esame senza chiedere conferma.
;		   Prompt   Esegue l'esame dopo aver chiesto conferma.
;
; SaveLog	Determina come ScanDisk debba utilizzare il file registro di
;		riparazione:
;		   Off	      (Predefinito) Non salva il file registro di
;			      riparazione.
;		   Append     Allega il file registro di riparazione ad un
;			      eventuale file precedente.
;		   Overwrite  Sostituisce il nuovo file registro di
;			      riparazione al precedente.
;
; Undo		Determina se ScanDisk debba creare un dischetto Annulla.
;		Il valore predefinito Š (ScanDisk non crea un dischetto
;		Annulla). Il valore Prompt invita ScanDisk a chiedere di
;		inserire un dischetto.

[CUSTOM]
   DriveSummary  = Auto         ; Auto, On, Off
   AllSummary    = Auto         ; Auto, On, Off
   Surface       = Never        ; Never, Always, Prompt
   CheckHost     = Never        ; Never, Always, Prompt
   SaveLog       = Off          ; Off, Append, Overwrite
   Undo          = Prompt       ; Prompt, Never

; I seguenti parametri determinano quali azioni correttive debbano essere
; attuate da ScanDisk se, eseguito con l'opzione /CUSTOM, rilevasse
; un errore nel disco.

; I cinque parametri che seguono accettano ognuno dei seguenti valori:
;    Prompt	ScanDisk chiede la conferma prima di risolvere il problema.
;    Fix	ScanDisk risolve il problema senza chiedere conferma.
;    Quit	ScanDisk viene terminato se rileva un problema specifico.

   DS_Header	 = Prompt	; Intestazione del file DoubleSpace
				; danneggiata
   FAT_Media	 = Prompt	; FAT mancante o non valido
   Okay_Entries  = Prompt	; Directory/file danneggiati ma riparabili
   Bad_Chain	 = Prompt	; File o directory che devono essere troncati
   Crosslinks	 = Prompt	; Collegamenti incrociati al livello FAT


; I sette parametri che seguono accettano ognuno dei seguenti valori:
;    Prompt	ScanDisk chiede la conferma prima di risolvere il problema.
;    Fix	ScanDisk risolve il problema senza chiedere conferma.
;    Quit	ScanDisk viene terminato se rileva un problema specifico.
;    Skip	ScanDisk non risolve un problema specifico, ma continua
;		l'esame del disco.

   Boot_Sector	 = Prompt	; Settore d'avvio danneggiato nell'unit…
				; DoubleSpace
   Invalid_MDFAT = Prompt	; Voci MDFAT non valide
   DS_Crosslinks = Prompt	; Collegamenti incrociati (MDFAT-level) non
				; validi
   DS_LostClust  = Prompt	; Cluster interni perduti
   DS_Signatures = Prompt	; Firme del volume DoubleSpace mancanti
   Mismatch_FAT  = Prompt	; Disparit… FAT su unit… non DoubleSpace
   Bad_Clusters  = Prompt	; Errore fisico o di espansione


; Il parametro che segue accetta ognuno dei seguenti valori:
;
;    Prompt	ScanDisk chiede la conferma prima di risolvere il problema.
;    Delete	ScanDisk elimina le voci delle directory danneggiate senza
;		chiedere conferma.
;    Quit	ScanDisk viene terminato se rileva un problema specifico.

   Bad_Entries	 = Prompt	; Directory/file danneggiati irreparabilmente


; Il parametro che segue accetta ognuno dei seguenti valori:
;
;    Prompt	ScanDisk chiede la conferma prima di risolvere il problema.
;    Save	ScanDisk salva i cluster perduti con un nome di file nella
;		radice senza chiedere conferma.
;    Delete	ScanDisk elimina il contenuto dei cluster danneggiati senza
;		chiedere conferma.
;    Quit	ScanDisk viene terminato se rileva un problema specifico.
;    Skip	ScanDisk non risolve un problema specifico, ma continua
;		l'esame del disco.

   LostClust	 = Prompt	; Clusters perduti
